# Retail Inventory - EF Core 8.0 Hands-On Exercises

A console application that walks through the EF Core 8.0 guided lab sheet using a
retail inventory scenario (products, categories, stock levels).

## Tech Stack
- .NET 8
- EF Core 8.0 (SQL Server provider)
- EFCore.BulkExtensions (bulk operations)

## Project Structure
```
RetailInventory/
├── RetailInventory.sln
├── .gitignore
├── README.md
└── RetailInventory/
    ├── RetailInventory.csproj
    ├── Program.cs                # Menu-driven runner, one method per lab
    ├── Data/
    │   └── AppDbContext.cs       # DbContext, relationships, seed data
    ├── Models/
    │   ├── Category.cs
    │   ├── Product.cs
    │   ├── ProductDetail.cs      # one-to-one with Product
    │   └── Tag.cs                # many-to-many with Product
    ├── DTOs/
    │   └── ProductDTO.cs         # used to avoid circular reference issues
    └── Migrations/               # generated by `dotnet ef migrations add`
```

## Getting Started

1. **Update the connection string**
   Open `RetailInventory/Data/AppDbContext.cs` and update the connection string
   inside `OnConfiguring` to point at your SQL Server / LocalDB instance.

2. **Restore packages**
   ```bash
   cd RetailInventory
   dotnet restore
   ```

3. **Create the database with migrations**
   ```bash
   dotnet tool install --global dotnet-ef   # once, if not already installed
   dotnet ef migrations add InitialCreate
   dotnet ef database update
   ```

4. **Run the app**
   ```bash
   dotnet run
   ```
   You'll get an interactive menu to run each lab's demo independently.

## Lab -> Code Mapping

| Lab | Topic | Where |
|---|---|---|
| 1 | ORM concepts, EF Core vs EF6 | conceptual, see below |
| 2 | Models + DbContext setup | `Models/`, `Data/AppDbContext.cs` |
| 3 | CLI migrations | `dotnet ef migrations add` / `dotnet ef database update` |
| 4 | Insert initial data | `Program.cs -> Lab4_InsertInitialData` |
| 5 | Retrieve data | `Program.cs -> Lab5_RetrieveData` |
| 6 | Update / delete | `Program.cs -> Lab6_UpdateAndDelete` |
| 7 | LINQ queries | `Program.cs -> Lab7_LinqQueries` |
| 8 | Schema change (StockQuantity) | `Models/Product.cs` + new migration |
| 9 | Seed data via `HasData()` | `Data/AppDbContext.cs -> OnModelCreating` |
| 10 | Eager / explicit / lazy loading | `Program.cs -> Lab10_LoadingStrategies` |
| 11 | One-to-one & many-to-many | `Models/ProductDetail.cs`, `Models/Tag.cs`, `Program.cs -> Lab11_Relationships` |
| 12 | Circular references | `DTOs/ProductDTO.cs`, `Program.cs -> Lab12_CircularReferenceHandling` |
| 13 | AsNoTracking + compiled queries | `Program.cs -> Lab13_NoTrackingAndCompiledQuery` |
| 14 | Bulk operations | `Program.cs -> Lab14_BulkOperations` |
| 15 | Concurrency with RowVersion | `Models/Product.cs (RowVersion)`, `Program.cs -> Lab15_ConcurrencyHandling` |

### Lab 1 notes (conceptual)
- **ORM**: EF Core maps C# classes (`Product`, `Category`) to SQL Server tables, so
  queries and updates are written against objects instead of raw SQL, which speeds up
  development and keeps the schema and code in sync.
- **EF Core vs EF Framework (EF6)**: EF Core is cross-platform and lightweight and
  supports LINQ, async queries, and compiled queries; EF6 is Windows-only, more
  mature, but less flexible for modern app architectures.
- **EF Core 8 highlights used here**: automatic many-to-many join table configuration,
  `HasData()` seeding, compiled async queries, and `AsNoTracking()` for read-only
  reporting scenarios.

## Notes
- Lazy loading (Lab 10, optional) requires installing
  `Microsoft.EntityFrameworkCore.Proxies`, calling `UseLazyLoadingProxies()` in
  `OnConfiguring`, and marking navigation properties `virtual`. It's intentionally
  left disabled by default since eager/explicit loading is generally the safer,
  more predictable choice.
- Bulk operations (Lab 14) use `EFCore.BulkExtensions`, which is much faster than
  `SaveChangesAsync()` for large batches because it avoids one round trip per row.
